spring:
  application:
    name: 06_Resilience4j_CircuitBreaker_App

# actuator end points 
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# circuit breaker properties
resilience4j.circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
        

